config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'
  get 'home', to: 'pages#home'
  get 'linklist', to: 'pages#linklist'
  get 'vuetest01', to: 'pages#vuetest01'
  resources :guides
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guide.rb
class Guide < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController
  before_action :set_guide, only: [:show, :edit, :update, :destroy]

  # GET /guides
  # GET /guides.json
  def index
    @guides = Guide.all
  end

  # GET /guides/1
  # GET /guides/1.json
  def show
  end

  # GET /guides/new
  def new
    @guide = Guide.new
  end

  # GET /guides/1/edit
  def edit
  end

  # POST /guides
  # POST /guides.json
  def create
    @guide = Guide.new(guide_params)

    respond_to do |format|
      if @guide.save
        format.html { redirect_to @guide, notice: 'Guide was successfully created.' }
        format.json { render :show, status: :created, location: @guide }
      else
        format.html { render :new }
        format.json { render json: @guide.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guides/1
  # PATCH/PUT /guides/1.json
  def update
    respond_to do |format|
      if @guide.update(guide_params)
        format.html { redirect_to @guide, notice: 'Guide was successfully updated.' }
        format.json { render :show, status: :ok, location: @guide }
      else
        format.html { render :edit }
        format.json { render json: @guide.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guides/1
  # DELETE /guides/1.json
  def destroy
    @guide.destroy
    respond_to do |format|
      format.html { redirect_to guides_url, notice: 'Guide was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guide
      @guide = Guide.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guide_params
      params.require(:guide).permit(:title)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def linklist
  end

  def vuetest01
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guides_helper.rb
module GuidesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/guides/_form.html.erb
<%= form_with(model: guide, local: true) do |form| %>
  <% if guide.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(guide.errors.count, "error") %> prohibited this guide from being saved:</h2>

      <ul>
      <% guide.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :guide_title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/guides/edit.html.erb
<h1>Editing Guide</h1>

<%= render 'form', guide: @guide %>

<%= link_to 'Show', @guide %> |
<%= link_to 'Back', guides_path %>

app/views/guides/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Guides</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @guides.each do |guide| %>
      <tr>
        <td><%= guide.title %></td>
        <td><%= link_to 'Show', guide %></td>
        <td><%= link_to 'Edit', edit_guide_path(guide) %></td>
        <td><%= link_to 'Destroy', guide, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Guide', new_guide_path %>

app/views/guides/new.html.erb
<h1>New Guide</h1>

<%= render 'form', guide: @guide %>

<%= link_to 'Back', guides_path %>

app/views/guides/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @guide.title %>
</p>

<%= link_to 'Edit', edit_guide_path(@guide) %> |
<%= link_to 'Back', guides_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestEnvApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <% if content_for? :for_head %>
      <%= yield :for_head %>
    <% end %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>You are on #home</h1>

app/views/pages/linklist.html.erb
<h1>You are on #linklist</h1>
<ul>
	<li><a href="https://devcenter.heroku.com/articles/getting-started-with-rails5">Getting Started on Heroku with Rails 5.x</a></li>
	<li><a href="https://devcenter.heroku.com/articles/getting-started-with-rails5">Set up Git</a></li>
	<li><a href="ttps://devcenter.heroku.com/articles/ruby-default-web-server">Heroku Procfile erforderlich? Puma ist default in Rails 5.</a></li>
	<li><a href="https://help.github.com/en/articles/adding-an-existing-project-to-github-using-the-command-line">Neues lokals Repository Push to Github.</a></li>
	<li><a href="https://devcenter.heroku.com/articles/github-integration">Automatic Deploys von Github Branch Master</a></li>
	

app/views/pages/vuetest01.html.erb
<% content_for :for_head do %>
  <!-- development version, includes helpful console warnings -->
  <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<% end %>
<h1>Vue-Test 01 - Adding Vue</h1>

<div id="app">
  <p>{{ message }}</p>
  <p>In der application.html.erb wie <a href="https://stackoverflow.com/questions/10225645/rails-override-head-page-element-when-using-a-partial-or-a-specific-controll">hier</a> erklärt Modifikation im Head eingefügt für diese Seite.
</div>

<script>
var app = new Vue({
  el: '#app',
  data: {
    message: 'Hello Vue!'
  }
})
</script>